#!/bin/bash
#By Yash Parekh
#July 22 2016
#This script is used to search google using chrome through the command line

#to run
#chmod u+x google
#./google (search term)

echo "Searching for $@"
for term in $@ ; do
	search="$search%20$term"
done
google-chrome "http://www.google.com/search?q=$search"
